name = "ShiftedArrays"
uuid = "1277b4bf-5013-50f5-be3d-901d8477a67a"
repo = "https://github.com/JuliaArrays/ShiftedArrays.jl.git"
version = "2.0.0"

[compat]
julia = "1"

[extras]
AbstractFFTs = "621f4979-c628-5d54-868e-fcf4e3e8185c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "AbstractFFTs"]
